<a href="https://colab.research.google.com/github/KeerthanaHM36/Pytorch/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***`PyTorch Tensors`***

In [ ]:
import torch

# Creating a 1D tensor
x = torch.tensor([1.0, 2.0, 3.0])
print('1D Tensor: \n', x)

# Creating a 2D tensor
y = torch.zeros((3, 3))
print('2D Tensor: \n', y)

1D Tensor: 
 tensor([1., 2., 3.])
2D Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


# ***`Operations on Tensors`***

In [ ]:
a = torch.tensor([1.0, 2.0])
b = torch.tensor([3.0, 4.0])

# Element-wise addition
print('Element Wise Addition of a & b: \n', a + b)

# Matrix multiplication
print('Matrix Multiplication of a & b: \n',
      torch.matmul(a.view(2, 1), b.view(1, 2)))

Element Wise Addition of a & b: 
 tensor([4., 6.])
Matrix Multiplication of a & b: 
 tensor([[3., 4.],
        [6., 8.]])


# ***`Reshaping and Transposing Tensors`***

In [ ]:
import torch
t = torch.tensor([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

# Reshaping
print("Reshaping")
print(t.reshape(6, 2))

# Resizing (deprecated, use reshape)
print("\nResizing")
print(t.view(2, 6))

# Transposing
print("\nTransposing")
print(t.transpose(0, 1))

Reshaping
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])

Resizing
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

Transposing
tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])


# ***`Autograd and Computational Graphs`***


In [ ]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2
y.backward()
print(x.grad)  #(dy/dx = 2x = 4 when x=2)

tensor(4.)


# ***`Building Neural Networks in PyTorch`***


In [ ]:
import torch
import torch.nn as nn

class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.fc1 = nn.Linear(10, 16)  # First layer
        self.fc2 = nn.Linear(16, 8)   # Second layer
        self.fc3 = nn.Linear(8, 1)    # Output layer

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = torch.sigmoid(self.fc3(x))
        return x

model = NeuralNetwork()
print(model)

NeuralNetwork(
  (fc1): Linear(in_features=10, out_features=16, bias=True)
  (fc2): Linear(in_features=16, out_features=8, bias=True)
  (fc3): Linear(in_features=8, out_features=1, bias=True)
)


# ***Define Loss Function and Optimizer***


In [ ]:
model = NeuralNetwork()
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

# ***`Train the Model`***


In [ ]:
inputs = torch.randn((100, 10))
targets = torch.randint(0, 2, (100, 1)).float()
epochs = 20

for epoch in range(epochs):
    optimizer.zero_grad()  # Reset gradients
    outputs = model(inputs)  # Forward pass
    loss = criterion(outputs, targets)  # Compute loss
    loss.backward()  # Compute gradients
    optimizer.step()  # Update weights

    if (epoch+1) % 5 == 0:
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")

Epoch [5/20], Loss: 0.6799
Epoch [10/20], Loss: 0.6568
Epoch [15/20], Loss: 0.6233
Epoch [20/20], Loss: 0.5810
